### ISSUE TITLE
TODO: API Structure

### ISSUE THREAD

**Issue by AkiaCode** [AkiaCode/Packages#2]
* [x] path: /
* [x] path: /search/{pacakge}
* [x] path: /search/{pacakge}?lang={lang}
* [x] path: /search/{pacakge}
* [x] path: /info/{paclage}
* [x] path: /info/{paclage}?lang={lang}
